"""enterprise baseline"""
from alembic import op
import sqlalchemy as sa
revision="20260812_0001";down_revision=None;branch_labels=None;depends_on=None
money=sa.Numeric(20,4)
def upgrade():
 op.create_table("ledger_entries",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("source_system",sa.String(30),nullable=False),sa.Column("source_id",sa.String(100),nullable=False),sa.Column("period",sa.String(7),nullable=False),sa.Column("account_code",sa.String(30),nullable=False),sa.Column("tax_code",sa.String(30),nullable=False),sa.Column("net_amount",money,nullable=False),sa.Column("tax_amount",money,nullable=False),sa.Column("lineage_json",sa.Text(),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.UniqueConstraint("tenant_id","source_system","source_id","content_hash"));op.create_index("ix_ledger_entries_tenant_id","ledger_entries",["tenant_id"])
 op.create_table("vat_reconciliations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("period",sa.String(7),nullable=False),sa.Column("ledger_tax",money,nullable=False),sa.Column("invoice_tax",money,nullable=False),sa.Column("return_tax",money,nullable=False),sa.Column("ledger_invoice_variance",money,nullable=False),sa.Column("ledger_return_variance",money,nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.String(40),nullable=False));op.create_index("ix_vat_reconciliations_tenant_id","vat_reconciliations",["tenant_id"])
 op.create_table("filing_workpapers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("period",sa.String(7),nullable=False),sa.Column("prepared_by",sa.String(100),nullable=False),sa.Column("reviewed_by",sa.String(100)),sa.Column("status",sa.String(20),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("payload_json",sa.Text(),nullable=False),sa.Column("payload_hash",sa.String(64),nullable=False),sa.UniqueConstraint("tenant_id","period"));op.create_index("ix_filing_workpapers_tenant_id","filing_workpapers",["tenant_id"])
 op.create_table("audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("payload_json",sa.Text(),nullable=False),sa.Column("occurred_at",sa.String(40),nullable=False),sa.Column("previous_hash",sa.String(64),nullable=False),sa.Column("event_hash",sa.String(64),nullable=False));op.create_index("ix_audit_events_tenant_id","audit_events",["tenant_id"])
def downgrade():
 for table in ("audit_events","filing_workpapers","vat_reconciliations","ledger_entries"): op.drop_table(table)
